%%
%% GX Framework
%% Copyright (c) 2009 Steve Davis <steven.charles.davis@gmail.com>. All rights reserved.
%% LICENSE: Creative Commons Non-Commercial License V 3.0 
%% http://creativecommons.org/licenses/by-nc/3.0/us/
%%
-module(gx_events).
-vsn("0.3").
-author('steve@simulacity.com').

%% NOTE: This module is not used, and may never 
%% need to be used

-export([wx/1]).

wx(calendar_day_changed) -> undefined;
wx(calendar_doubleclicked) -> undefined;
wx(calendar_month_changed) -> changed;
wx(calendar_sel_changed) -> undefined;
wx(calendar_weekday_clicked) -> undefined;
wx(calendar_year_changed) -> undefined;
wx('char') -> undefined;
wx(char_hook) -> undefined;
wx(close_window) -> onunload;
wx(command_button_clicked) -> onclick;
wx(command_checkbox_clicked) -> onselect;
wx(command_choice_selected) -> onselect;
wx(command_colourpicker_changed) -> onchange;
wx(command_combobox_selected) -> onselect;
wx(command_dirpicker_changed) -> onchange;
wx(command_filepicker_changed) -> undefined; 
wx(command_fontpicker_changed ) -> undefined;
wx(command_list_begin_drag ) -> undefined;
wx(command_list_begin_label_edit ) -> undefined;
wx(command_list_begin_rdrag ) -> undefined;
wx(command_list_cache_hint ) -> undefined;
wx(command_list_col_begin_drag ) -> undefined;
wx(command_list_col_click ) -> undefined;
wx(command_list_col_dragging) -> undefined;
wx(command_list_col_end_drag) -> undefined;
wx(command_list_col_right_click) -> undefined;
wx(command_list_delete_all_items) -> undefined;
wx(command_list_delete_item) -> undefined;
wx(command_list_end_label_edit) -> undefined;
wx(command_list_insert_item) -> undefined;
wx(command_list_item_activated) -> undefined;
wx(command_list_item_deselected) -> undefined;
wx(command_list_item_focused) -> undefined;
wx(command_list_item_middle_click) -> undefined;
wx(command_list_item_right_click) -> undefined;
wx(command_list_item_selected) -> undefined;
wx(command_list_key_down) -> undefined;
wx(command_listbox_doubleclicked) -> undefined;
wx(command_listbox_selected) -> undefined;
wx(command_menu_selected) -> undefined;
wx(command_notebook_page_changed) -> undefined;
wx(command_notebook_page_changing) -> undefined;
wx(command_radiobox_selected) -> undefined;
wx(command_radiobutton_selected) -> onselect;
wx(command_scrollbar_updated) -> undefined;
wx(command_slider_updated) -> undefined;
wx(command_text_enter) -> undefined;
wx(command_text_updated) -> onchange;
wx(command_togglebutton_clicked) -> undefined;
wx(command_tree_begin_drag) -> undefined;
wx(command_tree_begin_label_edit) -> undefined;
wx(command_tree_begin_rdrag) -> undefined;
wx(command_tree_delete_item) -> undefined;
wx(command_tree_end_drag) -> undefined;
wx(command_tree_end_label_edit) -> undefined;
wx(command_tree_get_info) -> undefined;
wx(command_tree_item_activated) -> undefined;
wx(command_tree_item_collapsed) -> undefined;
wx(command_tree_item_collapsing) -> undefined;
wx(command_tree_item_expanded) -> undefined;
wx(command_tree_item_expanding) -> undefined;
wx(command_tree_item_gettooltip) -> undefined;
wx(command_tree_item_menu) -> undefined;
wx(command_tree_item_middle_click) -> undefined;
wx(command_tree_item_right_click) -> undefined;
wx(command_tree_key_down) -> undefined;
wx(command_tree_sel_changed) -> undefined;
wx(command_tree_sel_changing) -> undefined;
wx(command_tree_set_info) -> undefined;
wx(command_tree_state_image_click) -> undefined;
wx(command_vlbox_selected) -> undefined;
wx(context_menu) -> undefined;
wx(create) -> undefined;
wx(date_changed) -> undefined;
wx(destroy) -> undefined;
wx(detailed_help) -> undefined;
wx(display_changed) -> undefined;
wx(end_session) -> undefined;
wx(enter_window) -> undefined;
wx(erase_background) -> undefined;
wx(grid_cell_begin_drag) -> undefined;
wx(grid_cell_change) -> undefined;
wx(grid_cell_left_click) -> undefined;
wx(grid_cell_left_dclick) -> undefined;
wx(grid_cell_right_click) -> undefined;
wx(grid_cell_right_dclick) -> undefined;
wx(grid_col_size) -> undefined;
wx(grid_editor_created) -> undefined;
wx(grid_editor_hidden) -> undefined;
wx(grid_editor_shown) -> undefined;
wx(grid_label_left_click) -> undefined;
wx(grid_label_left_dclick) -> undefined;
wx(grid_label_right_click) -> undefined;
wx(grid_label_right_dclick) -> undefined;
wx(grid_range_select) -> undefined;
wx(grid_row_size) -> undefined;
wx(grid_select_cell) -> undefined;
wx(help) -> undefined;
wx(iconize) -> undefined;
wx(idle) -> undefined;
wx(joy_button_down) -> undefined;
wx(joy_button_up) -> undefined;
wx(joy_move) -> undefined;
wx(joy_zmove) -> undefined;
wx(key_down) -> undefined;
wx(key_up) -> undefined;
wx(kill_focus) -> undefined;
wx(leave_window) -> undefined;
wx(left_dclick) -> undefined;
wx(left_down) -> undefined;
wx(left_up) -> undefined;
wx(maximize) -> undefined;
wx(menu_close) -> undefined;
wx(menu_highlight) -> undefined;
wx(menu_open) -> undefined;
wx(middle_dclick) -> undefined;
wx(middle_down) -> undefined;
wx(middle_up) -> undefined;
wx(motion) -> undefined;
wx(mouse_capture_changed) -> undefined;
wx(mousewheel) -> undefined;
wx(move) -> undefined;
wx(navigation_key) -> undefined;
wx(nc_enter_window) -> undefined;
wx(nc_leave_window) -> undefined;
wx(nc_left_dclick) -> undefined;
wx(nc_left_down) -> undefined;
wx(nc_left_up) -> undefined;
wx(nc_middle_dclick) -> undefined;
wx(nc_middle_down) -> undefined;
wx(nc_middle_up) -> undefined;
wx(nc_motion) -> undefined;
wx(nc_paint) -> undefined;
wx(nc_right_dclick) -> undefined;
wx(nc_right_down) -> undefined;
wx(nc_right_up) -> undefined;
wx(paint) -> undefined;
wx(paint_icon) -> undefined;
wx(palette_changed) -> undefined;
wx(query_end_session) -> undefined;
wx(query_new_palette) -> undefined;
wx(right_dclick) -> undefined;
wx(right_down) -> undefined;
wx(right_up) -> undefined;
wx(sash_dragged) -> undefined;
wx(scroll_bottom) -> undefined;
wx(scroll_changed) -> undefined;
wx(scroll_linedown) -> undefined;
wx(scroll_lineup) -> undefined;
wx(scroll_pagedown) -> undefined;
wx(scroll_pageup) -> undefined;
wx(scroll_thumbrelease) -> undefined;
wx(scroll_thumbtrack) -> undefined;
wx(scroll_top) -> undefined;
wx(scrollwin_bottom) -> undefined;
wx(scrollwin_linedown) -> undefined;
wx(scrollwin_lineup) -> undefined;
wx(scrollwin_pagedown) -> undefined;
wx(scrollwin_pageup) -> undefined;
wx(scrollwin_thumbrelease) -> undefined;
wx(scrollwin_thumbtrack) -> undefined;
wx(scrollwin_top) -> undefined;
wx(set_cursor) -> undefined;
wx(set_focus) -> undefined;
wx(show) -> undefined;
wx(size) -> undefined;
wx(stc_autocomp_selection) -> undefined;
wx(stc_calltip_click) -> undefined;
wx(stc_change) -> undefined;
wx(stc_charadded) -> undefined;
wx(stc_do_drop) -> undefined;
wx(stc_doubleclick) -> undefined;
wx(stc_drag_over) -> undefined;
wx(stc_dwellend) -> undefined;
wx(stc_dwellstart) -> undefined;
wx(stc_hotspot_click) -> undefined;
wx(stc_hotspot_dclick) -> undefined;
wx(stc_key) -> undefined;
wx(stc_macrorecord) -> undefined;
wx(stc_marginclick) -> undefined;
wx(stc_modified) -> undefined;
wx(stc_needshown) -> undefined;
wx(stc_painted) -> undefined;
wx(stc_romodifyattempt) -> undefined;
wx(stc_savepointleft) -> undefined;
wx(stc_savepointreached) -> undefined;
wx(stc_start_drag) -> undefined;
wx(stc_styleneeded) -> undefined;
wx(stc_updateui) -> undefined;
wx(stc_uridropped) -> undefined;
wx(stc_userlistselection) -> undefined;
wx(stc_zoom) -> undefined;
wx(sys_colour_changed) -> undefined;
wx(update_ui) -> undefined;
wx(_) -> error.
	
